doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            brand_ann:
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Brand'
                is_bundle: false
                prefix: App\Domain\Brand
            category_ann:
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Category'
                is_bundle: false
                prefix: App\Domain\Category
            model_ann:
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Model'
                is_bundle: false
                prefix: App\Domain\Model
