framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            query_bus: 'sync://'
            command_bus: 'sync://'
            # This Will be async
            event_bus: 'sync://'
            local_event_bus: 'sync://'
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Domain\CommandInterface': command_bus
            'App\Domain\QueryInterface': query_bus
            'App\Domain\EventInterface': [event_bus, local_event_bus]
