version:  '3.3'
services:
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './docker/nginx/certs:/etc/ssl/tuvalum/:ro'
      - '.:/var/www'
    ports:
      - "8001:80"
      - "445:443"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    user: $UID:$GID
    restart: on-failure
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      XDEBUG_MODE: coverage
      APP_NODE: 'php-fpm'
      JWT_PASSPHRASE: $JWT_PASSPHRASE
    volumes:
      - '.:/var/www'
  mysql:
    image: mysql:5.7
    hostname: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    ports:
      - "3308:3306"
  redis:
    image: redis:6-alpine
    ports:
      - '8445:8443'
      - '6381:6379'
volumes:
  mysql-datavolume:
