App\Domain\Brand\Create\CreateBrandCommand:
    properties:
        uuid:
            - NotBlank: ~

App\Domain\Brand\Find\FindBrandsQuery:
    properties:
        uuid:
            - NotBlank: ~
            - Uuid: ~
