App\Domain\Brand\Create\CreateBrandCommand:
    properties:
        name:
            - NotBlank: ~
        url:
            - Valid: ~
        slogan:
            - Valid: ~
        description:
            - Valid: ~
        shortDescription:
            - Valid: ~
        important:
            - Valid: ~
        position:
            - Valid: ~

App\Domain\Brand\Find\FindBrandsQuery:
    properties:
        uuid:
            - NotBlank: ~
            - Uuid: ~
